apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
